'use strict';

const test = require('node:test');
const assert = require('node:assert');
const fs = require('fs');
const os = require('os');
const path = require('path');

const gcode = require('../src/server/gcode');
const { Printer } = require('../src/server/printer');

// piccolo PNG 1x1 in base64
const PNG_1PX = 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAEhQGAhKmMIQAAAABJRU5ErkJggg==';

function makeGcode(layers = 20, movesPerLayer = 40) {
  const lines = [
    '; generated by PrusaSlicer 2.8.1+win64 on 2026-09-24',
    ';',
    `; thumbnail begin 1x1 ${PNG_1PX.length}`,
    `; ${PNG_1PX}`,
    '; thumbnail end',
    'M73 P0 R12',
    'M140 S60',
    'M104 S200',
    'M190 S60',
    'M109 S200',
    'G28 ; home',
    'G90',
    'M83',
  ];
  for (let l = 0; l < layers; l++) {
    lines.push(';LAYER_CHANGE', `;Z:${((l + 1) * 0.2).toFixed(1)}`, `G1 Z${((l + 1) * 0.2).toFixed(2)} F600`);
    for (let i = 0; i < movesPerLayer; i++) {
      const x = 50 + (i % 10) * 5;
      const y = 50 + Math.floor(i / 10) * 5;
      lines.push(`G1 X${x} Y${y} E0.2 F1800 ; perimetro`);
    }
    if (l === Math.floor(layers / 2)) lines.push('M73 P50 R6');
  }
  lines.push('M104 S0', 'M140 S0', 'M84');
  lines.push('; filament used [mm] = 1234.5', '; filament used [g] = 3.7', '; estimated printing time (normal mode) = 12m 30s', '; layer_height = 0.2', '; filament_type = PLA');
  return lines.join('\n') + '\n';
}

function tmpFile(content) {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'polipo-test-'));
  const p = path.join(dir, 'test.gcode');
  fs.writeFileSync(p, content);
  return p;
}

function waitFor(fn, timeout = 20000, what = 'condizione') {
  return new Promise((resolve, reject) => {
    const start = Date.now();
    const iv = setInterval(() => {
      let ok = false;
      try { ok = fn(); } catch (_) { ok = false; }
      if (ok) { clearInterval(iv); resolve(); }
      else if (Date.now() - start > timeout) { clearInterval(iv); reject(new Error('Timeout in attesa di: ' + what)); }
    }, 20);
  });
}

function makePrinter(extra = {}) {
  return new Printer({
    id: 'test',
    name: 'Test',
    port: 'VIRTUAL',
    extruders: 1,
    pause: { retract: 2, lift: 5 },
    scripts: {},
  }, { virtualOptions: { speed: 1000, record: true, startupDelay: 50, ...extra } });
}

function fileCommands(content) {
  return content.split('\n').map((l) => gcode.stripComment(l)).filter(Boolean).map(gcode.normalizeCommand);
}

test('checksum e parsing delle risposte', () => {
  assert.strictEqual(gcode.checksum('N0 M110 N0'), 125);
  const t = gcode.parseTemperatures('ok T:210.5 /210.0 B:60.1 /60.0 @:127 B@:0');
  assert.deepStrictEqual(t.tools.T0, { actual: 210.5, target: 210 });
  assert.deepStrictEqual(t.bed, { actual: 60.1, target: 60 });
  const multi = gcode.parseTemperatures(' T:200.0 /200.0 B:55.0 /55.0 T0:200.0 /200.0 T1:150.0 /0.0 @:0 B@:0');
  assert.deepStrictEqual(Object.keys(multi.tools), ['T0', 'T1']);
  assert.strictEqual(multi.tools.T1.target, 0);
  assert.strictEqual(gcode.parseTemperatures('echo:busy: processing'), null);
  assert.strictEqual(gcode.parseTemperatures('X:0.00 Y:0.00 Z:0.00 E:0.00 Count X:0 Y:0 Z:0'), null);
  assert.deepStrictEqual(gcode.parsePosition('X:10.00 Y:20.50 Z:0.30 E:1.00 Count X:800 Y:1640 Z:120'), { x: 10, y: 20.5, z: 0.3, e: 1 });
  const fw = gcode.parseFirmwareInfo('FIRMWARE_NAME:Marlin 2.1.2.1 (Jul 1 2023) SOURCE_CODE_URL:github.com/MarlinFirmware/Marlin PROTOCOL_VERSION:1.0 MACHINE_TYPE:Ender-3 V2 EXTRUDER_COUNT:1 UUID:cede2a2f');
  assert.strictEqual(fw.MACHINE_TYPE, 'Ender-3 V2');
  assert.strictEqual(fw.FIRMWARE_NAME, 'Marlin 2.1.2.1 (Jul 1 2023)');
  assert.strictEqual(gcode.parseDurationText('1d 2h 3m 4s'), 93784);
  assert.strictEqual(gcode.normalizeCommand('m117 Ciao Mondo ; commento'), 'M117 Ciao Mondo');
});

test('analisi di un file G-code', async () => {
  const p = tmpFile(makeGcode(10, 10));
  const meta = await gcode.analyzeFile(p);
  assert.strictEqual(meta.slicer, 'PrusaSlicer');
  assert.strictEqual(meta.estimatedTime, 750);
  assert.strictEqual(meta.filamentLength, 1234.5);
  assert.strictEqual(meta.filamentWeight, 3.7);
  assert.strictEqual(meta.layerCount, 10);
  assert.strictEqual(meta.material, 'PLA');
  assert.strictEqual(meta.nozzleTemp, 200);
  assert.strictEqual(meta.bedTemp, 60);
  assert.ok(meta.thumbnail && meta.thumbnail.base64 === PNG_1PX);
  assert.deepStrictEqual([meta.bounds.minX, meta.bounds.maxX, meta.bounds.maxZ], [50, 95, 2]);
});

test('connessione alla stampante virtuale', async () => {
  const printer = makePrinter();
  await printer.connect();
  try {
    assert.strictEqual(printer.state, 'operational');
    await waitFor(() => printer.firmware && printer.autoreport, 5000, 'firmware');
    assert.match(printer.firmware.name, /Marlin/);
    printer.setTemperature('T0', 200);
    printer.setTemperature('bed', 60);
    await waitFor(() => printer.temps.tools.T0.actual > 190 && printer.temps.bed.actual > 55, 10000, 'temperature');
    assert.strictEqual(printer.temps.tools.T0.target, 200);
    assert.ok(printer.tempHistory.length > 0);
  } finally {
    await printer.disconnect();
  }
  assert.strictEqual(printer.state, 'offline');
});

test('stampa completa con errori di trasmissione (resend)', async () => {
  const content = makeGcode(15, 30);
  const file = { name: 'test.gcode', path: tmpFile(content), meta: { layerCount: 15, estimatedTime: 750 } };
  const printer = makePrinter({ errorRate: 0.08 });
  await printer.connect();
  try {
    const vp = printer.transport.printer;
    await waitFor(() => printer.clearToSend && printer.queue.length === 0, 5000, 'coda vuota');
    vp.record.length = 0;
    // registra il layer a ogni commento del file (gli eventi 'update' sono limitati a 4 al secondo)
    let maxLayer = 0;
    const jobComment = printer._jobComment.bind(printer);
    printer._jobComment = (c) => { jobComment(c); maxLayer = Math.max(maxLayer, printer.job.layer); };
    printer.startPrint(file);
    assert.strictEqual(printer.state, 'printing');
    await waitFor(() => printer.lastJob && printer.lastJob.result === 'done', 30000, 'fine stampa');
    assert.strictEqual(printer.state, 'operational');
    assert.ok(printer.log.some((e) => /Reinvio/.test(e.text)), 'dovrebbero esserci stati dei resend');
    // tutti i comandi del file devono arrivare una sola volta e nell'ordine giusto
    const expected = fileCommands(content);
    const executed = vp.record.filter((c) => !/^M105$|^M155/.test(c));
    assert.deepStrictEqual(executed, expected);
    assert.strictEqual(maxLayer, 15, 'il layer corrente deve arrivare all\'ultimo');
  } finally {
    await printer.disconnect();
  }
});

test('pausa, ripresa e annullamento', async () => {
  const content = makeGcode(40, 60);
  const file = { name: 'lungo.gcode', path: tmpFile(content), meta: {} };
  const printer = makePrinter({ speed: 20 });
  await printer.connect();
  try {
    const vp = printer.transport.printer;
    await waitFor(() => printer.clearToSend && printer.queue.length === 0, 5000, 'coda vuota');
    printer.startPrint(file);
    await waitFor(() => printer.job && printer.job.layer >= 2, 20000, 'layer 2');
    printer.pause();
    await waitFor(() => printer.state === 'paused', 10000, 'pausa');
    const afterPause = vp.record.slice(-8).join(' | ');
    assert.match(afterPause, /G1 E-2 F2400/);
    assert.match(afterPause, /G1 Z5 F600/);
    const countWhilePaused = vp.record.length;
    await new Promise((r) => setTimeout(r, 300));
    assert.ok(vp.record.length - countWhilePaused <= 2, 'in pausa non devono partire righe del file');

    printer.resume();
    assert.strictEqual(printer.state, 'printing');
    await waitFor(() => vp.record.some((c, i) => i >= countWhilePaused && c === 'G1 Z-5 F600'), 5000, 'script di ripresa');
    await waitFor(() => printer.job && printer.job.layer >= 4, 20000, 'layer 4');

    printer.cancel();
    assert.ok(['cancelling', 'operational'].includes(printer.state));
    await waitFor(() => printer.state === 'operational', 10000, 'annullamento');
    assert.strictEqual(printer.lastJob.result, 'cancelled');
    assert.ok(vp.record.slice(-10).includes('M104 S0'));
    assert.ok(vp.record.slice(-10).includes('M84'));
  } finally {
    await printer.disconnect();
  }
});

test('arresto di emergenza', async () => {
  const printer = makePrinter();
  await printer.connect();
  try {
    printer.sendCommands(['M112']);
    assert.strictEqual(printer.state, 'error');
    assert.match(printer.error, /emergenza/i);
  } finally {
    await printer.disconnect();
  }
});
