'use strict';

// Genera un G-code di esempio (un portapenne esagonale con infill) in stile PrusaSlicer,
// con miniatura PNG, per provare Polipo con la stampante virtuale.
//   node scripts/make-sample.js [cartella]

const fs = require('fs');
const path = require('path');
const zlib = require('zlib');

const outDir = process.argv[2] || path.join(__dirname, '..', 'samples');
fs.mkdirSync(outDir, { recursive: true });

// --- PNG minimale -----------------------------------------------------------------
function crc32(buf) {
  let c, crc = 0xffffffff;
  for (let n = 0; n < buf.length; n++) {
    c = (crc ^ buf[n]) & 0xff;
    for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
    crc = (crc >>> 8) ^ c;
  }
  return (crc ^ 0xffffffff) >>> 0;
}
function chunk(type, data) {
  const len = Buffer.alloc(4); len.writeUInt32BE(data.length);
  const td = Buffer.concat([Buffer.from(type), data]);
  const crc = Buffer.alloc(4); crc.writeUInt32BE(crc32(td));
  return Buffer.concat([len, td, crc]);
}
function png(w, hgt, pixel) {
  const raw = Buffer.alloc((w * 4 + 1) * hgt);
  for (let y = 0; y < hgt; y++) {
    raw[y * (w * 4 + 1)] = 0;
    for (let x = 0; x < w; x++) {
      const [r, g, b, a] = pixel(x, y);
      const o = y * (w * 4 + 1) + 1 + x * 4;
      raw[o] = r; raw[o + 1] = g; raw[o + 2] = b; raw[o + 3] = a;
    }
  }
  const ihdr = Buffer.alloc(13);
  ihdr.writeUInt32BE(w, 0); ihdr.writeUInt32BE(hgt, 4);
  ihdr[8] = 8; ihdr[9] = 6; ihdr[10] = 0; ihdr[11] = 0; ihdr[12] = 0;
  return Buffer.concat([Buffer.from([137, 80, 78, 71, 13, 10, 26, 10]), chunk('IHDR', ihdr), chunk('IDAT', zlib.deflateSync(raw)), chunk('IEND', Buffer.alloc(0))]);
}

// miniatura: prisma esagonale visto in prospettiva
function thumbPixel(x, y, size) {
  const cx = size / 2, top = size * 0.2, bottom = size * 0.85, r = size * 0.3;
  const ry = r * 0.35;
  const inEllipse = (px, py, ecy) => ((px - cx) / r) ** 2 + ((py - ecy) / ry) ** 2 <= 1;
  if (inEllipse(x, y, top)) {
    const inner = ((x - cx) / (r * 0.8)) ** 2 + ((y - top) / (ry * 0.8)) ** 2 <= 1;
    return inner ? [120, 50, 10, 255] : [253, 186, 116, 255];
  }
  if (Math.abs(x - cx) <= r && y >= top && y <= bottom) {
    const shade = 0.55 + 0.45 * (1 - Math.abs(x - cx - r * 0.3) / (r * 1.3));
    const stripe = Math.floor((y - top) / 3) % 2 === 0 ? 1 : 0.94;
    return [Math.round(249 * shade * stripe), Math.round(115 * shade * stripe), Math.round(22 * shade * stripe), 255];
  }
  if (inEllipse(x, y, bottom)) return [200, 90, 20, 255];
  return [0, 0, 0, 0];
}

// --- G-code ------------------------------------------------------------------------
function hexagon(cx, cy, r, rot = 0) {
  const pts = [];
  for (let i = 0; i <= 6; i++) {
    const a = rot + (Math.PI / 3) * i;
    pts.push([cx + r * Math.cos(a), cy + r * Math.sin(a)]);
  }
  return pts;
}

// intervallo di un poligono convesso tagliato dalla retta y=c (orizzontale) o x=c
function scan(pts, horizontal, c) {
  const hits = [];
  for (let i = 0; i < pts.length - 1; i++) {
    const [ax, ay] = pts[i], [bx, by] = pts[i + 1];
    const [u1, v1, u2, v2] = horizontal ? [ax, ay, bx, by] : [ay, ax, by, bx];
    if ((v1 <= c && v2 >= c) || (v2 <= c && v1 >= c)) {
      if (v1 === v2) continue;
      hits.push(u1 + ((c - v1) / (v2 - v1)) * (u2 - u1));
    }
  }
  if (hits.length < 2) return null;
  return [Math.min(...hits) + 0.3, Math.max(...hits) - 0.3];
}

function makeGcode() {
  const layerH = 0.2;
  const layers = 150;
  const cx = 110, cy = 110;
  const eMm = 0.0333 * 1.0; // mm di filamento per mm di linea (0.45 x 0.2)
  const out = [];
  const size = 96;
  const thumb = png(size, size, (x, y) => thumbPixel(x, y, size)).toString('base64');
  const small = png(16, 16, (x, y) => thumbPixel(x * 6, y * 6, 96)).toString('base64');

  out.push('; generated by PrusaSlicer 2.8.1+win64 on 2026-09-24 at 10:00:00 UTC', '');
  for (const [w, b64] of [[16, small], [size, thumb]]) {
    out.push(';', `; thumbnail begin ${w}x${w} ${b64.length}`);
    for (let i = 0; i < b64.length; i += 78) out.push('; ' + b64.slice(i, i + 78));
    out.push('; thumbnail end', ';', '');
  }
  out.push('M73 P0 R38', 'M201 X1000 Y1000 Z200 E5000', 'M203 X200 Y200 Z12 E120', 'M107',
    ';TYPE:Custom', 'G90 ; use absolute coordinates', 'M83 ; extruder relative mode',
    'M140 S60 ; set bed temp', 'M104 S200 ; set extruder temp', 'M190 S60 ; wait for bed temp', 'M109 S200 ; wait for extruder temp',
    'G28 ; home all axes', 'G1 Z5 F3000', 'G1 X10 Y20 F6000', 'G1 Z0.28 F600',
    'G1 X10 Y200 E15 F1500 ; purge line', 'G1 X10.4 Y200 F3000', 'G1 X10.4 Y20 E15 F1500', 'G92 E0', '');

  let totalE = 30;
  const estimatedTime = 38 * 60 + 20;
  for (let l = 0; l < layers; l++) {
    const z = (l + 1) * layerH;
    if (l > 0 && l % Math.round(layers / 38) === 0) {
      const p = Math.round((l / layers) * 100);
      out.push(`M73 P${p} R${Math.max(0, Math.round(38 * (1 - l / layers)))}`);
    }
    out.push(';LAYER_CHANGE', `;Z:${z.toFixed(1)}`, `;HEIGHT:${layerH}`, 'G1 E-0.8 F2100', `G1 Z${(z + 0.4).toFixed(2)} F720`);
    const rot = (l * Math.PI) / 360; // leggera torsione
    const walls = [30, 29.55, 29.1];
    const first = hexagon(cx, cy, walls[0], rot)[0];
    out.push(`G1 X${first[0].toFixed(3)} Y${first[1].toFixed(3)} F9000`, `G1 Z${z.toFixed(2)} F720`, 'G1 E0.8 F2100');
    if (l === 1) out.push('M106 S255');
    for (const r of walls) {
      out.push(';TYPE:Perimeter');
      const pts = hexagon(cx, cy, r, rot);
      out.push(`G1 X${pts[0][0].toFixed(3)} Y${pts[0][1].toFixed(3)} F9000`);
      for (let i = 1; i < pts.length; i++) {
        const d = Math.hypot(pts[i][0] - pts[i - 1][0], pts[i][1] - pts[i - 1][1]);
        const e = d * eMm;
        totalE += e;
        out.push(`G1 X${pts[i][0].toFixed(3)} Y${pts[i][1].toFixed(3)} E${e.toFixed(5)} F${l === 0 ? 1200 : 2700}`);
      }
    }
    // fondo pieno per i primi 4 layer, poi solo pareti
    if (l < 4) {
      out.push(';TYPE:Solid infill');
      const poly = hexagon(cx, cy, 28.7, rot);
      const horizontal = l % 2 === 0;
      const vals = poly.map((p) => (horizontal ? p[1] : p[0]));
      const lo = Math.min(...vals) + 0.3, hi = Math.max(...vals) - 0.3;
      let n = 0;
      for (let c = lo; c <= hi; c += 0.45, n++) {
        const span = scan(poly, horizontal, c);
        if (!span || span[1] - span[0] < 0.5) continue;
        const [a, b] = n % 2 === 0 ? span : [span[1], span[0]];
        const p1 = horizontal ? [a, c] : [c, a];
        const p2 = horizontal ? [b, c] : [c, b];
        out.push(`G1 X${p1[0].toFixed(3)} Y${p1[1].toFixed(3)} F9000`);
        const e = Math.abs(b - a) * eMm;
        totalE += e;
        out.push(`G1 X${p2[0].toFixed(3)} Y${p2[1].toFixed(3)} E${e.toFixed(5)} F${l === 0 ? 1200 : 4000}`);
      }
    }
  }
  out.push('M73 P100 R0', ';TYPE:Custom', 'G1 E-2 F2100', 'G91', 'G1 Z10 F720', 'G90', 'G1 X0 Y200 F6000',
    'M104 S0', 'M140 S0', 'M107', 'M84', '');
  const grams = totalE * Math.PI * (1.75 / 2) ** 2 * 1.24 / 1000;
  out.push(`; filament used [mm] = ${totalE.toFixed(2)}`, `; filament used [g] = ${grams.toFixed(2)}`,
    `; estimated printing time (normal mode) = ${Math.floor(estimatedTime / 60)}m ${estimatedTime % 60}s`,
    '; filament_type = PLA', `; layer_height = ${layerH}`, '');
  return out.join('\n');
}

const file = path.join(outDir, 'portapenne-esagonale.gcode');
fs.writeFileSync(file, makeGcode());
console.log('Creato', file, (fs.statSync(file).size / 1024).toFixed(0) + ' KB');
